language: ruby
cache: bundler
rvm:
 - 2.3.8
before_install: 
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test 