# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.3.8-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.5-alpine  # service image
        environment:
          POSTGRES_USER: ralis-tutorial-ruby
          POSTGRES_DB: rails_tutorial
          POSTGRES_PASSWORD: ""

    working_directory: ~/rails-tutorials

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - rails-tutorial-v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - rails-tutorial-v1-dependencies-

      # install dependencies
      - run:
          name: install dependencies
          command: |
            gem update bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Cache Dependencies
      - save_cache:
          paths:
            - ./vendor/bundle
          key: rails-tutorial-v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Wait for DB to setup
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: 
          name: setup the database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rake

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

   # deployment
  
  deploy:
    docker:
      - image: buildpack-deps:trusty
        environment:
          HEROKU_APP_NAME: rails-tutorial-sample-app-gan
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


